language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: pytest test

after_success:
  - python3 core/core.py generate_solutions
  - if [[ $TRAVIS_EVENT_TYPE = cron ]]; then python3 core/core.py create_daily_task --token=$GITHUB_TOKEN; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: ./build/
